name: whisup
description: "Whisper your heart up."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1
  go_router: ^16.0.0
  intl: ^0.20.2
  rxdart: ^0.28.0
  unique_identifier: ^0.4.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/cert/
    # - assets/images/
    - assets/json/